title:              Team Creative
email:              jsy724724@gmail.com
description:        Bell Hackton 2021 
author:             Junseo Yang
baseurl:            "/"
url:                "https://sanghwasuh.github.io/"

# Social Profiles
twitter_username:   
github_username:    YouCanCallMeJ
facebook_username:  
instagram_username:  
linkedin_username:  junseo-yang-8878a6210

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
